enum ACTIONS {
  SET_ALL_CARS = 'SET_ALL_CARS',
  SET_NEW_CAR = 'SET_NEW_CAR',
  SET_EDIT_MODE = 'SET_EDIT_MODE',
  UPDATE_CAR_PARAMS = 'UPDATE_CAR_PARAMS',
  DELETE_CAR = 'DELETE_CAR',
  GENERATE_RANDOM_CARS = 'GENERATE_RANDOM_CARS',
  TOGGLE_GARAGE_PAGE = 'TOGGLE_GARAGE_PAGE',
  START_CAR_ENGINE = 'START_CAR_ENGINE',
}

export default ACTIONS;
